/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewComponentsRouteImport } from './routes/preview-components'
import { Route as IndexRouteImport } from './routes/index'

const PreviewComponentsRoute = PreviewComponentsRouteImport.update({
  id: '/preview-components',
  path: '/preview-components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview-components': typeof PreviewComponentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview-components': typeof PreviewComponentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview-components': typeof PreviewComponentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview-components'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview-components'
  id: '__root__' | '/' | '/preview-components'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewComponentsRoute: typeof PreviewComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview-components': {
      id: '/preview-components'
      path: '/preview-components'
      fullPath: '/preview-components'
      preLoaderRoute: typeof PreviewComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewComponentsRoute: PreviewComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
