/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewComponentsRouteImport } from './routes/preview-components'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminToolOutputsRouteImport } from './routes/admin.tool-outputs'
import { Route as AdminProfilesRouteImport } from './routes/admin.profiles'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminCampaignTrackingRouteImport } from './routes/admin.campaign-tracking'
import { Route as AdminAiConversationsRouteImport } from './routes/admin.ai-conversations'
import { Route as AdminAiConversationsIdRouteImport } from './routes/admin.ai-conversations.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewComponentsRoute = PreviewComponentsRouteImport.update({
  id: '/preview-components',
  path: '/preview-components',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolOutputsRoute = AdminToolOutputsRouteImport.update({
  id: '/tool-outputs',
  path: '/tool-outputs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignTrackingRoute = AdminCampaignTrackingRouteImport.update({
  id: '/campaign-tracking',
  path: '/campaign-tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiConversationsRoute = AdminAiConversationsRouteImport.update({
  id: '/ai-conversations',
  path: '/ai-conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiConversationsIdRoute = AdminAiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAiConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preview-components': typeof PreviewComponentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/ai-conversations': typeof AdminAiConversationsRouteWithChildren
  '/admin/campaign-tracking': typeof AdminCampaignTrackingRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/tool-outputs': typeof AdminToolOutputsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ai-conversations/$id': typeof AdminAiConversationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preview-components': typeof PreviewComponentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/ai-conversations': typeof AdminAiConversationsRouteWithChildren
  '/admin/campaign-tracking': typeof AdminCampaignTrackingRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/tool-outputs': typeof AdminToolOutputsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/admin/ai-conversations/$id': typeof AdminAiConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preview-components': typeof PreviewComponentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/ai-conversations': typeof AdminAiConversationsRouteWithChildren
  '/admin/campaign-tracking': typeof AdminCampaignTrackingRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/tool-outputs': typeof AdminToolOutputsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ai-conversations/$id': typeof AdminAiConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preview-components'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/admin/ai-conversations'
    | '/admin/campaign-tracking'
    | '/admin/partners'
    | '/admin/profiles'
    | '/admin/tool-outputs'
    | '/auth/callback'
    | '/admin/'
    | '/admin/ai-conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preview-components'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/admin/ai-conversations'
    | '/admin/campaign-tracking'
    | '/admin/partners'
    | '/admin/profiles'
    | '/admin/tool-outputs'
    | '/auth/callback'
    | '/admin'
    | '/admin/ai-conversations/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preview-components'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/admin/ai-conversations'
    | '/admin/campaign-tracking'
    | '/admin/partners'
    | '/admin/profiles'
    | '/admin/tool-outputs'
    | '/auth/callback'
    | '/admin/'
    | '/admin/ai-conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreviewComponentsRoute: typeof PreviewComponentsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-components': {
      id: '/preview-components'
      path: '/preview-components'
      fullPath: '/preview-components'
      preLoaderRoute: typeof PreviewComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tool-outputs': {
      id: '/admin/tool-outputs'
      path: '/tool-outputs'
      fullPath: '/admin/tool-outputs'
      preLoaderRoute: typeof AdminToolOutputsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaign-tracking': {
      id: '/admin/campaign-tracking'
      path: '/campaign-tracking'
      fullPath: '/admin/campaign-tracking'
      preLoaderRoute: typeof AdminCampaignTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-conversations': {
      id: '/admin/ai-conversations'
      path: '/ai-conversations'
      fullPath: '/admin/ai-conversations'
      preLoaderRoute: typeof AdminAiConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-conversations/$id': {
      id: '/admin/ai-conversations/$id'
      path: '/$id'
      fullPath: '/admin/ai-conversations/$id'
      preLoaderRoute: typeof AdminAiConversationsIdRouteImport
      parentRoute: typeof AdminAiConversationsRoute
    }
  }
}

interface AdminAiConversationsRouteChildren {
  AdminAiConversationsIdRoute: typeof AdminAiConversationsIdRoute
}

const AdminAiConversationsRouteChildren: AdminAiConversationsRouteChildren = {
  AdminAiConversationsIdRoute: AdminAiConversationsIdRoute,
}

const AdminAiConversationsRouteWithChildren =
  AdminAiConversationsRoute._addFileChildren(AdminAiConversationsRouteChildren)

interface AdminRouteChildren {
  AdminAiConversationsRoute: typeof AdminAiConversationsRouteWithChildren
  AdminCampaignTrackingRoute: typeof AdminCampaignTrackingRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminToolOutputsRoute: typeof AdminToolOutputsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiConversationsRoute: AdminAiConversationsRouteWithChildren,
  AdminCampaignTrackingRoute: AdminCampaignTrackingRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminToolOutputsRoute: AdminToolOutputsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreviewComponentsRoute: PreviewComponentsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
