/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as UpgradeProRouteImport } from './routes/upgrade-pro'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewComponentsRouteImport } from './routes/preview-components'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminWaitlistsRouteImport } from './routes/admin.waitlists'
import { Route as AdminToolOutputsRouteImport } from './routes/admin.tool-outputs'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminServiceOrdersRouteImport } from './routes/admin.service-orders'
import { Route as AdminProfilesRouteImport } from './routes/admin.profiles'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminContentResourcesRouteImport } from './routes/admin.content-resources'
import { Route as AdminCohortsRouteImport } from './routes/admin.cohorts'
import { Route as AdminCohortApplicationsRouteImport } from './routes/admin.cohort-applications'
import { Route as AdminCampaignTrackingRouteImport } from './routes/admin.campaign-tracking'
import { Route as AdminAiConversationsRouteImport } from './routes/admin.ai-conversations'
import { Route as AdminAdminLogsRouteImport } from './routes/admin.admin-logs'
import { Route as AdminAiConversationsIdRouteImport } from './routes/admin.ai-conversations.$id'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeProRoute = UpgradeProRouteImport.update({
  id: '/upgrade-pro',
  path: '/upgrade-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewComponentsRoute = PreviewComponentsRouteImport.update({
  id: '/preview-components',
  path: '/preview-components',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/tracks/$slug',
  path: '/tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistsRoute = AdminWaitlistsRouteImport.update({
  id: '/waitlists',
  path: '/waitlists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolOutputsRoute = AdminToolOutputsRouteImport.update({
  id: '/tool-outputs',
  path: '/tool-outputs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceOrdersRoute = AdminServiceOrdersRouteImport.update({
  id: '/service-orders',
  path: '/service-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentResourcesRoute = AdminContentResourcesRouteImport.update({
  id: '/content-resources',
  path: '/content-resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortsRoute = AdminCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortApplicationsRoute = AdminCohortApplicationsRouteImport.update({
  id: '/cohort-applications',
  path: '/cohort-applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignTrackingRoute = AdminCampaignTrackingRouteImport.update({
  id: '/campaign-tracking',
  path: '/campaign-tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiConversationsRoute = AdminAiConversationsRouteImport.update({
  id: '/ai-conversations',
  path: '/ai-conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/admin-logs',
  path: '/admin-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiConversationsIdRoute = AdminAiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAiConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-advisor': typeof AiAdvisorRoute
  '/apply': typeof ApplyRoute
  '/circles': typeof CirclesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preview-components': typeof PreviewComponentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/upgrade-pro': typeof UpgradeProRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/admin-logs': typeof AdminAdminLogsRoute
  '/admin/ai-conversations': typeof AdminAiConversationsRouteWithChildren
  '/admin/campaign-tracking': typeof AdminCampaignTrackingRoute
  '/admin/cohort-applications': typeof AdminCohortApplicationsRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/content-resources': typeof AdminContentResourcesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/service-orders': typeof AdminServiceOrdersRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tool-outputs': typeof AdminToolOutputsRoute
  '/admin/waitlists': typeof AdminWaitlistsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ai-conversations/$id': typeof AdminAiConversationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/apply': typeof ApplyRoute
  '/circles': typeof CirclesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preview-components': typeof PreviewComponentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/upgrade-pro': typeof UpgradeProRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/admin-logs': typeof AdminAdminLogsRoute
  '/admin/ai-conversations': typeof AdminAiConversationsRouteWithChildren
  '/admin/campaign-tracking': typeof AdminCampaignTrackingRoute
  '/admin/cohort-applications': typeof AdminCohortApplicationsRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/content-resources': typeof AdminContentResourcesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/service-orders': typeof AdminServiceOrdersRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tool-outputs': typeof AdminToolOutputsRoute
  '/admin/waitlists': typeof AdminWaitlistsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/ai-conversations/$id': typeof AdminAiConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-advisor': typeof AiAdvisorRoute
  '/apply': typeof ApplyRoute
  '/circles': typeof CirclesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preview-components': typeof PreviewComponentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/upgrade-pro': typeof UpgradeProRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/admin-logs': typeof AdminAdminLogsRoute
  '/admin/ai-conversations': typeof AdminAiConversationsRouteWithChildren
  '/admin/campaign-tracking': typeof AdminCampaignTrackingRoute
  '/admin/cohort-applications': typeof AdminCohortApplicationsRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/content-resources': typeof AdminContentResourcesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/service-orders': typeof AdminServiceOrdersRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tool-outputs': typeof AdminToolOutputsRoute
  '/admin/waitlists': typeof AdminWaitlistsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ai-conversations/$id': typeof AdminAiConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-advisor'
    | '/apply'
    | '/circles'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preview-components'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/upgrade-pro'
    | '/workshops'
    | '/admin/admin-logs'
    | '/admin/ai-conversations'
    | '/admin/campaign-tracking'
    | '/admin/cohort-applications'
    | '/admin/cohorts'
    | '/admin/content-resources'
    | '/admin/partners'
    | '/admin/profiles'
    | '/admin/service-orders'
    | '/admin/subscriptions'
    | '/admin/testimonials'
    | '/admin/tool-outputs'
    | '/admin/waitlists'
    | '/auth/callback'
    | '/services/$slug'
    | '/stories/$slug'
    | '/tools/$slug'
    | '/tracks/$slug'
    | '/admin/'
    | '/admin/ai-conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/apply'
    | '/circles'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preview-components'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/upgrade-pro'
    | '/workshops'
    | '/admin/admin-logs'
    | '/admin/ai-conversations'
    | '/admin/campaign-tracking'
    | '/admin/cohort-applications'
    | '/admin/cohorts'
    | '/admin/content-resources'
    | '/admin/partners'
    | '/admin/profiles'
    | '/admin/service-orders'
    | '/admin/subscriptions'
    | '/admin/testimonials'
    | '/admin/tool-outputs'
    | '/admin/waitlists'
    | '/auth/callback'
    | '/services/$slug'
    | '/stories/$slug'
    | '/tools/$slug'
    | '/tracks/$slug'
    | '/admin'
    | '/admin/ai-conversations/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-advisor'
    | '/apply'
    | '/circles'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preview-components'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/upgrade-pro'
    | '/workshops'
    | '/admin/admin-logs'
    | '/admin/ai-conversations'
    | '/admin/campaign-tracking'
    | '/admin/cohort-applications'
    | '/admin/cohorts'
    | '/admin/content-resources'
    | '/admin/partners'
    | '/admin/profiles'
    | '/admin/service-orders'
    | '/admin/subscriptions'
    | '/admin/testimonials'
    | '/admin/tool-outputs'
    | '/admin/waitlists'
    | '/auth/callback'
    | '/services/$slug'
    | '/stories/$slug'
    | '/tools/$slug'
    | '/tracks/$slug'
    | '/admin/'
    | '/admin/ai-conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiAdvisorRoute: typeof AiAdvisorRoute
  ApplyRoute: typeof ApplyRoute
  CirclesRoute: typeof CirclesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreviewComponentsRoute: typeof PreviewComponentsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  UpgradeProRoute: typeof UpgradeProRoute
  WorkshopsRoute: typeof WorkshopsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  TracksSlugRoute: typeof TracksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade-pro': {
      id: '/upgrade-pro'
      path: '/upgrade-pro'
      fullPath: '/upgrade-pro'
      preLoaderRoute: typeof UpgradeProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-components': {
      id: '/preview-components'
      path: '/preview-components'
      fullPath: '/preview-components'
      preLoaderRoute: typeof PreviewComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/tracks/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlists': {
      id: '/admin/waitlists'
      path: '/waitlists'
      fullPath: '/admin/waitlists'
      preLoaderRoute: typeof AdminWaitlistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tool-outputs': {
      id: '/admin/tool-outputs'
      path: '/tool-outputs'
      fullPath: '/admin/tool-outputs'
      preLoaderRoute: typeof AdminToolOutputsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-orders': {
      id: '/admin/service-orders'
      path: '/service-orders'
      fullPath: '/admin/service-orders'
      preLoaderRoute: typeof AdminServiceOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-resources': {
      id: '/admin/content-resources'
      path: '/content-resources'
      fullPath: '/admin/content-resources'
      preLoaderRoute: typeof AdminContentResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohorts': {
      id: '/admin/cohorts'
      path: '/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AdminCohortsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohort-applications': {
      id: '/admin/cohort-applications'
      path: '/cohort-applications'
      fullPath: '/admin/cohort-applications'
      preLoaderRoute: typeof AdminCohortApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaign-tracking': {
      id: '/admin/campaign-tracking'
      path: '/campaign-tracking'
      fullPath: '/admin/campaign-tracking'
      preLoaderRoute: typeof AdminCampaignTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-conversations': {
      id: '/admin/ai-conversations'
      path: '/ai-conversations'
      fullPath: '/admin/ai-conversations'
      preLoaderRoute: typeof AdminAiConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-logs': {
      id: '/admin/admin-logs'
      path: '/admin-logs'
      fullPath: '/admin/admin-logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-conversations/$id': {
      id: '/admin/ai-conversations/$id'
      path: '/$id'
      fullPath: '/admin/ai-conversations/$id'
      preLoaderRoute: typeof AdminAiConversationsIdRouteImport
      parentRoute: typeof AdminAiConversationsRoute
    }
  }
}

interface AdminAiConversationsRouteChildren {
  AdminAiConversationsIdRoute: typeof AdminAiConversationsIdRoute
}

const AdminAiConversationsRouteChildren: AdminAiConversationsRouteChildren = {
  AdminAiConversationsIdRoute: AdminAiConversationsIdRoute,
}

const AdminAiConversationsRouteWithChildren =
  AdminAiConversationsRoute._addFileChildren(AdminAiConversationsRouteChildren)

interface AdminRouteChildren {
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAiConversationsRoute: typeof AdminAiConversationsRouteWithChildren
  AdminCampaignTrackingRoute: typeof AdminCampaignTrackingRoute
  AdminCohortApplicationsRoute: typeof AdminCohortApplicationsRoute
  AdminCohortsRoute: typeof AdminCohortsRoute
  AdminContentResourcesRoute: typeof AdminContentResourcesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminServiceOrdersRoute: typeof AdminServiceOrdersRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminToolOutputsRoute: typeof AdminToolOutputsRoute
  AdminWaitlistsRoute: typeof AdminWaitlistsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAiConversationsRoute: AdminAiConversationsRouteWithChildren,
  AdminCampaignTrackingRoute: AdminCampaignTrackingRoute,
  AdminCohortApplicationsRoute: AdminCohortApplicationsRoute,
  AdminCohortsRoute: AdminCohortsRoute,
  AdminContentResourcesRoute: AdminContentResourcesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminServiceOrdersRoute: AdminServiceOrdersRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminToolOutputsRoute: AdminToolOutputsRoute,
  AdminWaitlistsRoute: AdminWaitlistsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAdvisorRoute: AiAdvisorRoute,
  ApplyRoute: ApplyRoute,
  CirclesRoute: CirclesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreviewComponentsRoute: PreviewComponentsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  UpgradeProRoute: UpgradeProRoute,
  WorkshopsRoute: WorkshopsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  TracksSlugRoute: TracksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
